name: QA Pipeline

on:
  workflow_run:
    workflows: ["CI"]      # Se dispara cuando termina el CI de StockPulse (el repo principal)
    types: [completed]
  pull_request:
    branches: [main]       # En PRs internos al repo de QA, corre regresión
  push:
    branches: [main]

jobs:
  e2e-smoke:
    name: E2E Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Tests
        # Pasamos variables de entorno (En un entorno real usaríamos GitHub Secrets)
        env:
          API_URL: ${{ secrets.STAGING_API_URL }}
          UI_URL: ${{ secrets.STAGING_UI_URL }}
        run: npx playwright test --grep @smoke

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-smoke-report
          path: playwright-report/
          retention-days: 15

  e2e-regression:
    name: E2E Regression Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Regression Tests
        env:
          API_URL: ${{ secrets.STAGING_API_URL }}
          UI_URL: ${{ secrets.STAGING_UI_URL }}
          DB_HOST: ${{ secrets.STAGING_DB_HOST }}
          DB_PORT: 5432
          DB_NAME: stockpulse_test
          DB_USER: ${{ secrets.STAGING_DB_USER }}
          DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
        run: npx playwright test --grep @regression

      - name: Upload Regression Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-regression-report
          path: playwright-report/
          retention-days: 15

  api-contract:
    name: API Contract Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run api-tests/postman/StockPulse.postman_collection.json --env-var "baseUrl=${{ secrets.STAGING_API_URL }}"
